name: Metrics
on:
  # Schedule daily updates
  schedule: [{ cron: "0 0 * * *" }]
  workflow_dispatch:
  # (optional) Run workflow when pushing on main
  push: { branches: ["main"] }
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: drcount-root
          config_timezone: Asia/Kolkata
          committer_message: "chore: update metrics"
          template: classic
          base: header, activity, community, repositories, metadata

          plugin_calendar: yes # Enables the contributions calendar
          plugin_calendar_limit: 4 # Limits it to the last 4 years (2022, 2023, 2024, 2025)

          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year # Shows full-year activity for the latest year only (2025)

          plugin_languages: yes
          plugin_languages_details: bytes-size, percentage
