name: Metrics
on:
  # Schedule daily updates
  schedule: [{ cron: "0 0 * * *" }]
  workflow_dispatch:
  # (optional) Run workflow when pushing on main
  push: { branches: ["main"] }
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: drcount-root
          config_timezone: Asia/Kolkata
          committer_message: "chore: update metrics"
          template: classic
          base: header, activity, community, repositories, metadata

          plugin_calendar: yes # Enables the contributions calendar
          plugin_calendar_limit: 3 # Limits it to the last 3 years (2022, 2023, 2024)

          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year # Shows full-year activity for the latest year only (2024)

          plugin_languages: yes
          plugin_languages_details: bytes-size, percentage

          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_threshold: X

          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: yes

          plugin_licenses: yes
          plugin_licenses_setup: npm ci

          plugin_skyline: yes
          plugin_skyline_year: 2022 # Displays skyline from 2022 onward
          plugin_skyline_frames: 120
          plugin_skyline_quality: 1

          plugin_stargazers: yes
          plugin_stargazers_charts_type: chartist

          plugin_support: yes
          plugin_topics: yes
          plugin_topics_limit: 0
          plugin_topics_mode: icons
